<a href="https://colab.research.google.com/github/fdhliakbar/IR-Lab/blob/main/P09_Link_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def hits_algorithm(adjacency_matrix, max_iter=100, tol=1e-6):
    n = adjacency_matrix.shape[0]
    authority_scores = np.ones(n)
    hub_scores = np.ones(n)

    for _ in range(max_iter):
        prev_authority_scores = authority_scores.copy()
        prev_hub_scores = hub_scores.copy()

        # Update Authority: a = A^T * h
        new_authority_scores = np.dot(adjacency_matrix.T, hub_scores)

        # Update Hub: h = A * a
        new_hub_scores = np.dot(adjacency_matrix, new_authority_scores)

        # Normalisasi (L2 norm)
        norm_a = np.linalg.norm(new_authority_scores, 2)
        if norm_a != 0:
            authority_scores = new_authority_scores / norm_a

        norm_h = np.linalg.norm(new_hub_scores, 2)
        if norm_h != 0:
            hub_scores = new_hub_scores / norm_h

        # Cek konvergensi
        if (np.linalg.norm(authority_scores - prev_authority_scores, 2) < tol and
            np.linalg.norm(hub_scores - prev_hub_scores, 2) < tol):
            break

    return authority_scores, hub_scores

adjacency_matrix = np.array([
    [0, 1, 1, 0],
    [0, 0, 1, 1],
    [0, 0, 0, 1],
    [0, 0, 0, 0]
])

authority, hub = hits_algorithm(adjacency_matrix)

print("--- Hasil Algoritma HITS ---")
print("Matriks Adjacency:\n", adjacency_matrix)
print("\nNilai Authority (a):", authority)
print("Nilai Hub (h):", hub)

--- Hasil Algoritma HITS ---
Matriks Adjacency:
 [[0 1 1 0]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 0 0]]

Nilai Authority (a): [0.         0.32798493 0.73697604 0.59100948]
Nilai Hub (h): [0.59100875 0.73697636 0.32798552 0.        ]
